from __future__ import annotations

from typing import List, Optional

from src.db_mysql import Db, NotFoundError, ValidationError, DbError
from models.match_event import MatchEvent


class MatchEventRepository:
    def __init__(self, db: Db):
        self.db = db

    # -------------------------
    # Basic reads
    # -------------------------
    def get_by_id(self, event_id: int) -> MatchEvent:
        sql = """
        SELECT event_id, match_id, player_id, team_id, minute, event_type, xg, created_at
        FROM match_event
        WHERE event_id=%s
        """
        with self.db.conn() as cnx, self.db.cursor(cnx) as cur:
            cur.execute(sql, (event_id,))
            row = cur.fetchone()
            if not row:
                raise NotFoundError(f"MatchEvent {event_id} not found")
            return MatchEvent(**row)

    def list_by_match(self, match_id: int) -> List[MatchEvent]:
        sql = """
        SELECT event_id, match_id, player_id, team_id, minute, event_type, xg, created_at
        FROM match_event
        WHERE match_id=%s
        ORDER BY minute, created_at, event_id
        """
        with self.db.conn() as cnx, self.db.cursor(cnx) as cur:
            cur.execute(sql, (match_id,))
            return [MatchEvent(**r) for r in cur.fetchall()]

    # -------------------------
    # Inserts / updates
    # -------------------------
    def insert(self, e: MatchEvent) -> int:
        """
        created_at is always generated by the database (NOW()) to avoid NULL issues.
        """
        sql = """
        INSERT INTO match_event (match_id, player_id, team_id, minute, event_type, xg, created_at)
        VALUES (%s, %s, %s, %s, %s, %s, NOW())
        """
        with self.db.conn() as cnx, self.db.cursor(cnx) as cur:
            cur.execute(
                sql,
                (e.match_id, e.player_id, e.team_id, e.minute, e.event_type, e.xg),
            )
            cnx.commit()
            return int(cur.lastrowid)

    def update(self, e: MatchEvent) -> None:
        """
        created_at is an audit field; we do not update it.
        """
        if e.event_id is None:
            raise ValueError("event_id is required")

        sql = """
        UPDATE match_event
        SET match_id=%s,
            player_id=%s,
            team_id=%s,
            minute=%s,
            event_type=%s,
            xg=%s
        WHERE event_id=%s
        """
        with self.db.conn() as cnx, self.db.cursor(cnx) as cur:
            cur.execute(
                sql,
                (e.match_id, e.player_id, e.team_id, e.minute, e.event_type, e.xg, e.event_id),
            )
            if cur.rowcount == 0:
                raise NotFoundError(f"MatchEvent {e.event_id} not found")
            cnx.commit()

    def delete(self, event_id: int) -> None:
        sql = "DELETE FROM match_event WHERE event_id=%s"
        with self.db.conn() as cnx, self.db.cursor(cnx) as cur:
            cur.execute(sql, (event_id,))
            if cur.rowcount == 0:
                raise NotFoundError(f"MatchEvent {event_id} not found")
            cnx.commit()

    # -------------------------
    # Transaction example (multi-table)
    # -------------------------
    def add_goal_transaction(
        self,
        match_id: int,
        team_id: int,
        player_id: Optional[int],
        minute: int,
        xg: Optional[float] = None,
    ) -> int:
        """
        Transaction:
          1) Lock match row (FOR UPDATE) and validate status
          2) Insert goal event (created_at via NOW())
          3) If match was scheduled, switch it to live
        """
        if minute < 0 or minute > 200:
            raise ValidationError("minute out of range (0..200)")

        with self.db.conn() as cnx:
            try:
                cnx.start_transaction()

                with self.db.cursor(cnx) as cur:
                    cur.execute(
                        "SELECT status FROM matches WHERE match_id=%s FOR UPDATE",
                        (match_id,),
                    )
                    row = cur.fetchone()
                    if not row:
                        raise NotFoundError(f"Match {match_id} not found")

                    status = row["status"]
                    if status in ("finished", "cancelled"):
                        raise ValidationError("cannot add event to finished/cancelled match")

                    cur.execute(
                        """
                        INSERT INTO match_event
                        (match_id, player_id, team_id, minute, event_type, xg, created_at)
                        VALUES (%s, %s, %s, %s, 'goal', %s, NOW())
                        """,
                        (match_id, player_id, team_id, minute, xg),
                    )
                    event_id = int(cur.lastrowid)

                    if status == "scheduled":
                        cur.execute(
                            "UPDATE matches SET status='live' WHERE match_id=%s",
                            (match_id,),
                        )

                cnx.commit()
                return event_id

            except Exception as e:
                cnx.rollback()
                if isinstance(e, (NotFoundError, ValidationError, DbError)):
                    raise
                raise DbError(f"Failed to add goal transaction: {e}") from e
